[project]
name = "mitol-django-hubspot-api"
version = "2023.5.10"

[tool.bumpver]
current_version = "2023.5.10"
version_pattern = "YYYY.MM.DD[.INC0]"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"__init__.py" = [
    '__version__ = "{version}"',
]