[project]
name = "mitol-django-google-sheets"
version = "2024.7.3"

[tool.bumpver]
current_version = "2024.7.3"
version_pattern = "YYYY.MM.DD[.INC0]"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"__init__.py" = [
    '__version__ = "{version}"',
]