[project]
name = "mitol-django-geoip"
version = "2023.11.13.1"

[tool.bumpver]
current_version = "2023.11.13.1"
version_pattern = "YYYY.MM.DD[.INC0]"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"__init__.py" = [
    '__version__ = "{version}"',
]