[project]
name = "mitol-django-google-sheets-refunds"
version = "2023.6.9"

[tool.bumpver]
current_version = "2023.6.9"
version_pattern = "YYYY.MM.DD[.INC0]"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"__init__.py" = [
    '__version__ = "{version}"',
]